# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "LTS"
    - nodejs_version: "Stable"

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@3
  - npm version
  - npm install

cache:
  - '%APPDATA%\npm-cache'

branches:
  except:
    - webpack-test

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - cmd: npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
